In [3]:
import pandas as pd
import numpy as np
import dataframe as df
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from tensorflow.keras import Sequential
import tensorflow as tf
from tensorflow.keras.layers import Dense
import keras_tuner as kf
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report

ModuleNotFoundError: No module named 'dataframe'

In [4]:
df = pd.read_csv("C:\\Users\\mdabd\\Downloads\\excelR\\Neural networks\\Neural networks\\Alphabets_data.csv")

In [5]:
df

letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  \
0          T     2     8      3       5      1     8    13      0      6   
1          I     5    12      3       7      2    10     5      5      4   
2          D     4    11      6       8      6    10     6      2      6   
3          N     7    11      6       6      3     5     9      4      6   
4          G     2     1      3       1      1     8     6      6      6   
...      ...   ...   ...    ...     ...    ...   ...   ...    ...    ...   
19995      D     2     2      3       3      2     7     7      7      6   
19996      C     7    10      8       8      4     4     8      6      9   
19997      T     6     9      6       7      5     6    11      3      7   
19998      S     2     3      4       2      1     8     7      2      6   
19999      A     4     9      6       6      2     9     5      3      1   

       xybar  x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
0          6      10       8      0       8      0       8  
1         13       3       9      2       8      4      10  
2         10       3       7      3       7      3       9  
3          4       4      10      6      10      2       8  
4          6       5       9      1       7      5      10  
...      ...     ...     ...    ...     ...    ...     ...  
19995      6       6       4      2       8      3       7  
19996     12       9      13      2       9      3       7  
19997     11       9       5      2      12      2       4  
19998     10       6       8      1       9      5       8  
19999      8       1       8      2       7      2       8  

[20000 rows x 17 columns]

In [6]:
df.drop(columns=['width','height'], inplace=True)

In [7]:
df

letter  xbox  ybox  onpix  xbar  ybar  x2bar  y2bar  xybar  x2ybar  \
0          T     2     8      1     8    13      0      6      6      10   
1          I     5    12      2    10     5      5      4     13       3   
2          D     4    11      6    10     6      2      6     10       3   
3          N     7    11      3     5     9      4      6      4       4   
4          G     2     1      1     8     6      6      6      6       5   
...      ...   ...   ...    ...   ...   ...    ...    ...    ...     ...   
19995      D     2     2      2     7     7      7      6      6       6   
19996      C     7    10      4     4     8      6      9     12       9   
19997      T     6     9      5     6    11      3      7     11       9   
19998      S     2     3      1     8     7      2      6     10       6   
19999      A     4     9      2     9     5      3      1      8       1   

       xy2bar  xedge  xedgey  yedge  yedgex  
0           8      0       8      0       8  
1           9      2       8      4      10  
2           7      3       7      3       9  
3          10      6      10      2       8  
4           9      1       7      5      10  
...       ...    ...     ...    ...     ...  
19995       4      2       8      3       7  
19996      13      2       9      3       7  
19997       5      2      12      2       4  
19998       8      1       9      5       8  
19999       8      2       7      2       8  

[20000 rows x 15 columns]

In [8]:
df.isna().sum()

letter    0
xbox      0
ybox      0
onpix     0
xbar      0
ybar      0
x2bar     0
y2bar     0
xybar     0
x2ybar    0
xy2bar    0
xedge     0
xedgey    0
yedge     0
yedgex    0
dtype: int64

In [9]:
#pd.get_dummies(data = df, columns = ['letter'])

In [10]:
df

letter  xbox  ybox  onpix  xbar  ybar  x2bar  y2bar  xybar  x2ybar  \
0          T     2     8      1     8    13      0      6      6      10   
1          I     5    12      2    10     5      5      4     13       3   
2          D     4    11      6    10     6      2      6     10       3   
3          N     7    11      3     5     9      4      6      4       4   
4          G     2     1      1     8     6      6      6      6       5   
...      ...   ...   ...    ...   ...   ...    ...    ...    ...     ...   
19995      D     2     2      2     7     7      7      6      6       6   
19996      C     7    10      4     4     8      6      9     12       9   
19997      T     6     9      5     6    11      3      7     11       9   
19998      S     2     3      1     8     7      2      6     10       6   
19999      A     4     9      2     9     5      3      1      8       1   

       xy2bar  xedge  xedgey  yedge  yedgex  
0           8      0       8      0       8  
1           9      2       8      4      10  
2           7      3       7      3       9  
3          10      6      10      2       8  
4           9      1       7      5      10  
...       ...    ...     ...    ...     ...  
19995       4      2       8      3       7  
19996      13      2       9      3       7  
19997       5      2      12      2       4  
19998       8      1       9      5       8  
19999       8      2       7      2       8  

[20000 rows x 15 columns]

In [11]:
label_encoder = LabelEncoder()

In [12]:
df["letter_encoded"] = label_encoder.fit_transform(df["letter"])

In [13]:
# Displaying the result
print(df)

      letter  xbox  ybox  onpix  xbar  ybar  x2bar  y2bar  xybar  x2ybar  \
0          T     2     8      1     8    13      0      6      6      10   
1          I     5    12      2    10     5      5      4     13       3   
2          D     4    11      6    10     6      2      6     10       3   
3          N     7    11      3     5     9      4      6      4       4   
4          G     2     1      1     8     6      6      6      6       5   
...      ...   ...   ...    ...   ...   ...    ...    ...    ...     ...   
19995      D     2     2      2     7     7      7      6      6       6   
19996      C     7    10      4     4     8      6      9     12       9   
19997      T     6     9      5     6    11      3      7     11       9   
19998      S     2     3      1     8     7      2      6     10       6   
19999      A     4     9      2     9     5      3      1      8       1   

       xy2bar  xedge  xedgey  yedge  yedgex  letter_encoded  
0           8      0     

In [14]:
df.drop(columns=['letter'],inplace=True)

In [15]:
df

xbox  ybox  onpix  xbar  ybar  x2bar  y2bar  xybar  x2ybar  xy2bar  \
0         2     8      1     8    13      0      6      6      10       8   
1         5    12      2    10     5      5      4     13       3       9   
2         4    11      6    10     6      2      6     10       3       7   
3         7    11      3     5     9      4      6      4       4      10   
4         2     1      1     8     6      6      6      6       5       9   
...     ...   ...    ...   ...   ...    ...    ...    ...     ...     ...   
19995     2     2      2     7     7      7      6      6       6       4   
19996     7    10      4     4     8      6      9     12       9      13   
19997     6     9      5     6    11      3      7     11       9       5   
19998     2     3      1     8     7      2      6     10       6       8   
19999     4     9      2     9     5      3      1      8       1       8   

       xedge  xedgey  yedge  yedgex  letter_encoded  
0          0       8      0       8              19  
1          2       8      4      10               8  
2          3       7      3       9               3  
3          6      10      2       8              13  
4          1       7      5      10               6  
...      ...     ...    ...     ...             ...  
19995      2       8      3       7               3  
19996      2       9      3       7               2  
19997      2      12      2       4              19  
19998      1       9      5       8              18  
19999      2       7      2       8               0  

[20000 rows x 15 columns]

In [16]:
df.rename(columns={'letter_encoded':'Letter'},inplace=True)

In [17]:
df

xbox  ybox  onpix  xbar  ybar  x2bar  y2bar  xybar  x2ybar  xy2bar  \
0         2     8      1     8    13      0      6      6      10       8   
1         5    12      2    10     5      5      4     13       3       9   
2         4    11      6    10     6      2      6     10       3       7   
3         7    11      3     5     9      4      6      4       4      10   
4         2     1      1     8     6      6      6      6       5       9   
...     ...   ...    ...   ...   ...    ...    ...    ...     ...     ...   
19995     2     2      2     7     7      7      6      6       6       4   
19996     7    10      4     4     8      6      9     12       9      13   
19997     6     9      5     6    11      3      7     11       9       5   
19998     2     3      1     8     7      2      6     10       6       8   
19999     4     9      2     9     5      3      1      8       1       8   

       xedge  xedgey  yedge  yedgex  Letter  
0          0       8      0       8      19  
1          2       8      4      10       8  
2          3       7      3       9       3  
3          6      10      2       8      13  
4          1       7      5      10       6  
...      ...     ...    ...     ...     ...  
19995      2       8      3       7       3  
19996      2       9      3       7       2  
19997      2      12      2       4      19  
19998      1       9      5       8      18  
19999      2       7      2       8       0  

[20000 rows x 15 columns]

In [18]:
#Model Building

In [19]:
df.drop(columns = ['Letter'])

xbox  ybox  onpix  xbar  ybar  x2bar  y2bar  xybar  x2ybar  xy2bar  \
0         2     8      1     8    13      0      6      6      10       8   
1         5    12      2    10     5      5      4     13       3       9   
2         4    11      6    10     6      2      6     10       3       7   
3         7    11      3     5     9      4      6      4       4      10   
4         2     1      1     8     6      6      6      6       5       9   
...     ...   ...    ...   ...   ...    ...    ...    ...     ...     ...   
19995     2     2      2     7     7      7      6      6       6       4   
19996     7    10      4     4     8      6      9     12       9      13   
19997     6     9      5     6    11      3      7     11       9       5   
19998     2     3      1     8     7      2      6     10       6       8   
19999     4     9      2     9     5      3      1      8       1       8   

       xedge  xedgey  yedge  yedgex  
0          0       8      0       8  
1          2       8      4      10  
2          3       7      3       9  
3          6      10      2       8  
4          1       7      5      10  
...      ...     ...    ...     ...  
19995      2       8      3       7  
19996      2       9      3       7  
19997      2      12      2       4  
19998      1       9      5       8  
19999      2       7      2       8  

[20000 rows x 14 columns]

In [ ]:
sc = StandardScaler()
x = df.drop(columns=['Letter'])
y = df['Letter']

In [ ]:
x

xbox  ybox  onpix  xbar  ybar  x2bar  y2bar  xybar  x2ybar  xy2bar  \
0         2     8      1     8    13      0      6      6      10       8   
1         5    12      2    10     5      5      4     13       3       9   
2         4    11      6    10     6      2      6     10       3       7   
3         7    11      3     5     9      4      6      4       4      10   
4         2     1      1     8     6      6      6      6       5       9   
...     ...   ...    ...   ...   ...    ...    ...    ...     ...     ...   
19995     2     2      2     7     7      7      6      6       6       4   
19996     7    10      4     4     8      6      9     12       9      13   
19997     6     9      5     6    11      3      7     11       9       5   
19998     2     3      1     8     7      2      6     10       6       8   
19999     4     9      2     9     5      3      1      8       1       8   

       xedge  xedgey  yedge  yedgex  
0          0       8      0       8  
1          2       8      4      10  
2          3       7      3       9  
3          6      10      2       8  
4          1       7      5      10  
...      ...     ...    ...     ...  
19995      2       8      3       7  
19996      2       9      3       7  
19997      2      12      2       4  
19998      1       9      5       8  
19999      2       7      2       8  

[20000 rows x 14 columns]

In [ ]:
y

0        19
1         8
2         3
3        13
4         6
         ..
19995     3
19996     2
19997    19
19998    18
19999     0
Name: Letter, Length: 20000, dtype: int64

In [ ]:
x = sc.fit_transform(x)
x

array([[-1.0576983 ,  0.29187713, -1.14401317, ..., -0.21908163,
        -1.4381527 ,  0.12291107],
       [ 0.51038497,  1.5023577 , -0.6874762 , ..., -0.21908163,
         0.12008142,  1.35944092],
       [-0.01230945,  1.19973756,  1.13867169, ..., -0.8656262 ,
        -0.26947711,  0.74117599],
       ...,
       [ 1.03307939,  0.59449727,  0.68213471, ...,  2.36709667,
        -0.65903564, -2.35014863],
       [-1.0576983 , -1.22122359, -1.14401317, ...,  0.42746295,
         0.50963994,  0.12291107],
       [-0.01230945,  0.59449727, -0.6874762 , ..., -0.8656262 ,
        -0.65903564,  0.12291107]])

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2, random_state=1)

In [ ]:
xtrain

array([[-0.53500387,  0.29187713,  0.22559774, ..., -0.21908163,
         0.89919847,  0.12291107],
       [ 0.51038497,  1.19973756,  0.68213471, ..., -0.8656262 ,
         1.67831553,  0.12291107],
       [ 1.03307939,  0.89711742,  0.68213471, ..., -0.21908163,
         0.89919847, -0.49535386],
       ...,
       [ 1.55577381,  0.59449727, -0.6874762 , ..., -0.21908163,
        -0.26947711, -2.35014863],
       [-0.53500387, -1.82646388, -0.23093923, ..., -2.15871536,
        -0.65903564,  0.12291107],
       [-0.01230945,  0.29187713, -0.23093923, ...,  1.07400752,
        -0.26947711, -1.73188371]])

In [ ]:
#Initialize model
ann = Sequential()

#Add hidden layer
ann.add(Dense(units=10,activation='relu'))

#Add output layer
ann.add(Dense(units=1, activation='sigmoid'))

#Establish the connection between the layers
ann.compile(optimizer = 'adadelta',loss='binary_crossentropy',metrics=['accuracy'])

#Fit the data
ann.fit(xtrain,ytrain, epochs=100)

Epoch 1/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.0540 - loss: -9.7169
Epoch 2/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0526 - loss: -9.7236
Epoch 3/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0527 - loss: -9.7285
Epoch 4/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0543 - loss: -9.9415
Epoch 5/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0484 - loss: -10.0609
Epoch 6/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0531 - loss: -10.4304
Epoch 7/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0516 - loss: -10.5385
Epoch 8/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0528 - loss: -10.6391
Epoch 9/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0534 - loss: -10.6439
Epoch 10/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0523 - loss: -10.8499
Epoch 11/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0490 - loss: -10.7670
Epoch 12/100
500/500 ━━

In [ ]:
xtest

array([[-0.01230945, -0.31336316, -0.23093923, ..., -0.21908163,
        -0.26947711,  0.12291107],
       [-1.0576983 , -1.22122359, -0.6874762 , ..., -0.21908163,
        -0.65903564, -0.49535386],
       [-0.53500387, -0.91860345, -1.14401317, ...,  1.7205521 ,
        -1.04859417,  0.12291107],
       ...,
       [ 4.16924591,  2.10759799,  0.22559774, ..., -0.8656262 ,
        -0.65903564, -0.49535386],
       [-0.01230945,  0.89711742, -0.23093923, ..., -0.8656262 ,
        -0.26947711,  0.74117599],
       [-1.0576983 , -0.6159833 , -0.6874762 , ..., -2.15871536,
        -0.65903564,  0.12291107]])

In [ ]:
ypred = ann.predict(xtest)
ypred

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


array([[0.6757548 ],
       [0.80152476],
       [0.9817119 ],
       ...,
       [0.94529104],
       [0.5588352 ],
       [0.69548374]], dtype=float32)

In [ ]:
ytest

11456     3
16528     3
3253     21
18614     1
1544      7
         ..
6375     25
14837    18
3931     20
18266     0
12028     0
Name: Letter, Length: 4000, dtype: int64

In [ ]:
ypred > 0.5

array([[ True],
       [ True],
       [ True],
       ...,
       [ True],
       [ True],
       [ True]])

In [ ]:
ypred = ypred > 0.5
ypred

array([[ True],
       [ True],
       [ True],
       ...,
       [ True],
       [ True],
       [ True]])

In [ ]:
ytest

11456     3
16528     3
3253     21
18614     1
1544      7
         ..
6375     25
14837    18
3931     20
18266     0
12028     0
Name: Letter, Length: 4000, dtype: int64

In [ ]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.22      0.15      0.18       162
           1       0.04      0.99      0.07       152
           2       0.00      0.00      0.00       144
           3       0.00      0.00      0.00       156
           4       0.00      0.00      0.00       139
           5       0.00      0.00      0.00       144
           6       0.00      0.00      0.00       154
           7       0.00      0.00      0.00       146
           8       0.00      0.00      0.00       138
           9       0.00      0.00      0.00       141
          10       0.00      0.00      0.00       137
          11       0.00      0.00      0.00       139
          12       0.00      0.00      0.00       145
          13       0.00      0.00      0.00       161
          14       0.00      0.00      0.00       173
          15       0.00      0.00      0.00       174
          16       0.00      0.00      0.00       159
          17       0.00    

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
#Hyperparameter Tunning

In [ ]:
import keras_tuner as kt

In [ ]:
def optimizer_selection(hp):
    #initialize the model
    model = Sequential()
    #Add hidden layer
    model.add(Dense(units=10, activation='relu'))
    #Add output layer
    model.add(Dense(units=1, activation='sigmoid'))
    #Optimizer selection
    optim = hp.Choice('optimizer', values = ['sgd','adam','rmsprop'])
    model.compile(optimizer=optim, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return model

In [ ]:
tuner = kt.RandomSearch(
    optimizer_selection,
    objective='val_accuracy',                     #val acc means the testing accuracy
    max_trials=3
)

In [ ]:
tuner.search(xtrain,ytrain, epochs = 3, validation_data = (xtest,ytest))

Trial 3 Complete [00h 00m 07s]
val_accuracy: 0.03799999877810478

Best val_accuracy So Far: 0.04050000011920929
Total elapsed time: 00h 00m 18s


In [ ]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'sgd'}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]
model.fit(xtrain,ytrain, epochs = 100, validation_data = (xtest,ytest))

Epoch 1/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.0403 - loss: nan - val_accuracy: 0.0405 - val_loss: nan
Epoch 2/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0408 - loss: nan - val_accuracy: 0.0405 - val_loss: nan
Epoch 3/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0416 - loss: nan - val_accuracy: 0.0405 - val_loss: nan
Epoch 4/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0414 - loss: nan - val_accuracy: 0.0405 - val_loss: nan
Epoch 5/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0382 - loss: nan - val_accuracy: 0.0405 - val_loss: nan
Epoch 6/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0392 - loss: nan - val_accuracy: 0.0405 - val_loss: nan
Epoch 7/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0385 - loss: nan - val_accuracy: 0.0405 - val_loss: nan
Epoch 8/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0384 - loss: nan - val_accuracy: 0.0405 - val_loss: nan
Epoch 9/100
500/

In [ ]:
model.evaluate(xtrain,ytrain)

500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.0380 - loss: nan


[nan, 0.03918749839067459]

In [ ]:
model.evaluate(xtest,ytest)

125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.0411 - loss: nan


[nan, 0.04050000011920929]